"""Kanban handler for project_feature tasks — the Coder role.

Reads repo summary → creates feature branch → runs CodeAgent in execute mode
→ opens PR against the configured staging branch.
"""
from __future__ import annotations

import asyncio
import logging

from workers.kanban import TaskHandler
from tools.project import resolve_agent_model
from tools.project.gitea_sync import push_files_to_gitea
from infra.settings import get_agent_setting
from workers.project_autonomy import check_autonomy
from infra.nocodb_client import NocodbClient
from tools.project.knowledge import read_repo_summary
from infra.config import resolve_model_entry

_log = logging.getLogger("project_feature.handler")
_DEFAULT_HUMAN_REVIEW_THRESHOLD = 5


async def handle(task: dict) -> dict:
    payload = task.get("input_payload") or {}
    return await asyncio.to_thread(_run, task, payload)


def _run(task: dict, payload: dict) -> dict:
    project_id = int(payload.get("project_id") or 0)
    feature_description = str(payload.get("feature_description") or "").strip()
    branch_name = str(payload.get("branch_name") or "").strip()
    architect_context = str(payload.get("architect_context") or "").strip()

    if not project_id or not feature_description or not branch_name:
        return {"status": "failed", "error": "project_id, feature_description, and branch_name are required"}

    db = NocodbClient()
    check_autonomy(db, task)

    model_role = resolve_agent_model(task, "project_agent")
    staging_branch = str(get_agent_setting(f"project:{project_id}", "staging_branch") or "staging")

    gitea = _get_gitea_client(db, project_id)
    if gitea is None:
        return {"status": "failed", "error": "no Gitea connection configured"}
    owner, repo_name = _get_repo_coords(db, project_id)

    repo_summary = read_repo_summary(db, project_id)

    model_entry = resolve_model_entry(model_role)
    if not model_entry:
        return {"status": "failed", "error": f"model role not in catalog: {model_role!r}"}
    model_id = str(model_entry.get("model_id") or model_role)

    try:
        gitea.create_branch(owner, repo_name, branch_name, from_branch=staging_branch)
    except Exception as exc:
        return {"status": "failed", "error": f"branch creation failed: {exc}"}

    try:
        result = _run_code_agent(
            db=db,
            project_id=project_id,
            model_id=model_id,
            feature_description=feature_description,
            architect_context=architect_context,
            repo_summary=repo_summary,
            task_id=str(task.get("Id") or ""),
        )
    except Exception as exc:
        _log.error("CodeAgent failed  project=%d  err=%s", project_id, exc, exc_info=True)
        return {"status": "failed", "error": f"CodeAgent failed: {exc}"}

    changed_paths: list[str] = result.get("changed_paths") or []
    pushed_paths = push_files_to_gitea(
        db, gitea, owner, repo_name, branch_name, project_id,
        changed_paths,
        commit_message=f"feat: {feature_description[:60]}",
    )

    try:
        pr = gitea.create_pr(
            owner, repo_name,
            title=f"feat: {feature_description[:72]}",
            head=branch_name,
            base=staging_branch,
            body=f"Auto-generated by project agent.\n\n{feature_description}",
        )
        pr_id = int(pr.get("number") or pr.get("id") or 0)
    except Exception as exc:
        _log.warning("PR creation failed  project=%d  branch=%s  err=%s", project_id, branch_name, exc)
        pr_id = 0

    tokens_used = int(result.get("tokens_used") or 0)
    _log.info(
        "project_feature done  project=%d  branch=%s  pr=%d  tokens=%d  pushed=%d",
        project_id, branch_name, pr_id, tokens_used, len(pushed_paths),
    )

    try:
        from workers import kanban as _kanban
        _kanban.submit(db, "project_index", {"project_id": project_id, "trigger": "post_feature"},
                       created_by=f"project:{project_id}", agent=f"project:{project_id}")
    except Exception as exc:
        _log.warning("project_feature: project_index enqueue failed  err=%s", exc)

    _enqueue_next(db, task, payload, project_id, pr_id, branch_name, feature_description, changed_paths)

    return {
        "status": "done",
        "pr_id": pr_id,
        "branch_name": branch_name,
        "commit_shas": result.get("commit_shas") or [],
        "change_summary": result.get("change_summary") or "",
        "tokens_used": tokens_used,
        "pushed_paths": pushed_paths,
    }


def _enqueue_next(
    db,
    task: dict,
    payload: dict,
    project_id: int,
    pr_id: int,
    branch_name: str,
    feature_description: str,
    changed_paths: list[str],
) -> None:
    from workers import kanban as _kanban

    threshold = int(get_agent_setting(f"project:{project_id}", "human_review_threshold_files") or _DEFAULT_HUMAN_REVIEW_THRESHOLD)
    file_count = len(changed_paths)

    base_payload = {
        "project_id": project_id,
        "pr_id": pr_id,
        "branch_name": branch_name,
        "feature_description": feature_description,
        "architect_context": str(payload.get("architect_context") or ""),
        "revision_count": int(payload.get("revision_count") or 0),
        "changed_paths": changed_paths,
        "parent_task_id": task.get("Id"),
    }

    if threshold > 0 and file_count >= threshold:
        _kanban.submit(
            db, "project_human_review", {**base_payload, "human_feedback": None},
            status="blocked",
            created_by=f"project:{project_id}",
            agent=f"project:{project_id}",
        )
    else:
        _kanban.submit(
            db, "project_review", base_payload,
            created_by=f"project:{project_id}",
            agent=f"project:{project_id}",
        )


def _run_code_agent(
    db,
    project_id: int,
    model_id: str,
    feature_description: str,
    architect_context: str,
    repo_summary: str,
    task_id: str,
) -> dict:
    from workers.code.agent import CodeAgent
    from shared.jobs import STORE

    user_message = feature_description
    extra_context = "\n\n".join(filter(None, [repo_summary, architect_context]))
    if extra_context:
        user_message = f"[Repo Context]\n{extra_context}\n\n[Task]\n{feature_description}"

    agent = CodeAgent(
        model=f"local:{model_id}",
        org_id=0,
        mode="execute",
        project_id=project_id,
        interactive_fs=True,
    )

    job = STORE.create()
    agent.run_job(job, user_message)

    tokens_used = sum(
        e.get("usage", {}).get("total_tokens", 0)
        for e in job.events
        if isinstance(e, dict)
    )
    file_changes = [e for e in job.events if isinstance(e, dict) and e.get("type") == "file_change"]
    changed_paths = list({e["path"] for e in file_changes if e.get("path")})

    return {
        "tokens_used": tokens_used,
        "commit_shas": [],
        "change_summary": f"{len(file_changes)} file(s) changed",
        "changed_paths": changed_paths,
    }


def _get_gitea_client(db, project_id: int):
    from infra.gitea_client import GiteaClient
    project = db.get_project(project_id)
    if not project:
        return None
    org_id = int(project.get("org_id") or 0)
    rows = db._safe_list("gitea_connections", f"(org_id,eq,{org_id})", limit=1)
    if not rows:
        return None
    conn = rows[0]
    return GiteaClient(
        base_url=str(conn.get("base_url") or ""),
        token=str(conn.get("access_token") or ""),
        username=str(conn.get("username") or ""),
    )


def _get_repo_coords(db, project_id: int) -> tuple[str, str]:
    """Return (owner, repo_name) from the project's gitea_origin field."""
    project = db.get_project(project_id)
    origin = str(project.get("gitea_origin") or "")
    if "/" in origin:
        parts = origin.rstrip("/").split("/")
        return parts[-2], parts[-1]
    return "", origin


_type_check: TaskHandler = handle
